export const moviesList = [
  {
    id: 1,
    title: "The Great Gatsby",
    year: "2013",
    runtime: "143",
    genres: ["Drama", "Romance"],
    director: "Baz Luhrmann",
    actors: "Lisa Adam, Frank Aldridge, Amitabh Bachchan, Steve Bisley",
    plot: "A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor, Jay Gatsby.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_SX300.jpg",
  },
  {
    id: 2,
    title: "The Theory of Everything",
    year: "2014",
    runtime: "123",
    genres: ["Biography", "Drama", "Romance"],
    director: "James Marsh",
    actors: "Eddie Redmayne, Felicity Jones, Tom Prior, Sophie Perry",
    plot: "A look at the relationship between the famous physicist Stephen Hawking and his wife.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAwMTU4MDA3NDNeQTJeQWpwZ15BbWU4MDk4NTMxNTIx._V1_SX300.jpg",
  },
  {
    id: 3,
    title: "Ratatouille",
    year: "2007",
    runtime: "111",
    genres: ["Animation", "Comedy", "Family"],
    director: "Brad Bird, Jan Pinkava",
    actors: "Patton Oswalt, Ian Holm, Lou Romano, Brian Dennehy",
    plot: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg",
  },
  {
    id: 4,
    title: "The Martian",
    year: "2015",
    runtime: "144",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    director: "Ridley Scott",
    actors: "Matt Damon, Jessica Chastain, Kristen Wiig, Jeff Daniels",
    plot: "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg",
  },
  {
    id: 5,
    title: "Stardust",
    year: "2007",
    runtime: "127",
    genres: ["Adventure", "Family", "Fantasy"],
    director: "Matthew Vaughn",
    actors: "Ian McKellen, Bimbo Hart, Alastair MacIntosh, David Kelly",
    plot: "In a countryside town bordering on a magical land, a young man makes a promise to his beloved that he'll retrieve a fallen star by venturing into the magical realm.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjkyMTE1OTYwNF5BMl5BanBnXkFtZTcwMDIxODYzMw@@._V1_SX300.jpg",
  },
  {
    id: 6,
    title: "Apocalypto",
    year: "2006",
    runtime: "139",
    genres: ["Action", "Adventure", "Drama"],
    director: "Mel Gibson",
    actors:
      "Rudy Youngblood, Dalia Hernández, Jonathan Brewer, Morris Birdyellowhead",
    plot: "As the Mayan kingdom faces its decline, the rulers insist the key to prosperity is to build more temples and offer human sacrifices. Jaguar Paw, a young man captured for sacrifice, flees to avoid his fate.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNTM1NjYyNTY5OV5BMl5BanBnXkFtZTcwMjgwNTMzMQ@@._V1_SX300.jpg",
  },
  {
    id: 7,
    title: "No Country for Old Men",
    year: "2007",
    runtime: "122",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Ethan Coen, Joel Coen",
    actors: "Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson",
    plot: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
  },

  {
    id: 8,
    title: "The Third Man",
    year: "1949",
    runtime: "93",
    genres: ["Mystery", "Thriller"],
    director: "Carol Reed",
    actors: "Joseph Cotten, Alida Valli, Orson Welles, Trevor Howard",
    plot: "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwNzMzMTQ0Ml5BMl5BanBnXkFtZTgwNjExMzUwNjE@._V1_SX300.jpg",
  },
  {
    id: 9,
    title: "The Imitation Game",
    year: "2014",
    runtime: "114",
    genres: ["Biography", "Drama", "Thriller"],
    director: "Morten Tyldum",
    actors:
      "Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear",
    plot: "During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1_SX300.jpg",
  },
  {
    id: 10,
    title: "Scarface",
    year: "1983",
    runtime: "170",
    genres: ["Crime", "Drama"],
    director: "Brian De Palma",
    actors:
      "Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio",
    plot: "In Miami in 1980, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAzOTM4MzEwNl5BMl5BanBnXkFtZTgwMzU1OTc1MDE@._V1_SX300.jpg",
  },
  {
    id: 11,
    title: "The Hateful Eight",
    year: "2015",
    runtime: "187",
    genres: ["Crime", "Drama", "Mystery"],
    director: "Quentin Tarantino",
    actors:
      "Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh, Walton Goggins",
    plot: "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg",
  },
  {
    id: 12,
    title: "Black Swan",
    year: "2010",
    runtime: "108",
    genres: ["Drama", "Thriller"],
    director: "Darren Aronofsky",
    actors: "Natalie Portman, Mila Kunis, Vincent Cassel, Barbara Hershey",
    plot: 'A committed dancer wins the lead role in a production of Tchaikovsky\'s "Swan Lake" only to find herself struggling to maintain her sanity.',
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
  },
  {
    id: 13,
    title: "Inception",
    year: "2010",
    runtime: "148",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Christopher Nolan",
    actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    plot: "A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
  },
  {
    id: 14,
    title: "Whiplash",
    year: "2014",
    runtime: "107",
    genres: ["Drama"],
    director: "Damien Chazelle",
    actors: "Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist",
    plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU4OTQ3MDUyMV5BMl5BanBnXkFtZTgwOTA2MjU0MjE@._V1_SX300.jpg",
  },
  {
    id: 15,
    title: "The Silence of the Lambs",
    year: "1991",
    runtime: "118",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Jonathan Demme",
    actors:
      "Jodie Foster, Lawrence A. Bonney, Kasi Lemmons, Lawrence T. Wrentz",
    plot: "A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SX300.jpg",
  },
  {
    id: 16,
    title: "Midnight Express",
    year: "1978",
    runtime: "121",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Alan Parker",
    actors: "Brad Davis, Irene Miracle, Bo Hopkins, Paolo Bonacelli",
    plot: "Billy Hayes, an American college student, is caught smuggling drugs out of Turkey and thrown into prison.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyMDA5MzkyOF5BMl5BanBnXkFtZTgwOTYwNTcxMTE@._V1_SX300.jpg",
  },
  {
    id: 17,
    title: "Pulp Fiction",
    year: "1994",
    runtime: "154",
    genres: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    actors: "Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta",
    plot: "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SX300.jpg",
  },
  {
    id: 18,
    title: "Lock, Stock and Two Smoking Barrels",
    year: "1998",
    runtime: "107",
    genres: ["Comedy", "Crime"],
    director: "Guy Ritchie",
    actors: "Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham",
    plot: "A botched card game in London triggers four friends, thugs, weed-growers, hard gangsters, loan sharks and debt collectors to collide with each other in a series of unexpected events, all for the sake of weed, cash and two antique shotguns.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyN2JmZmEtNjAyMy00NzYwLThmY2MtYWQ3OGNhNjExMmM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
  },
  {
    id: 19,
    title: "Rear Window",
    year: "1954",
    runtime: "112",
    genres: ["Mystery", "Thriller"],
    director: "Alfred Hitchcock",
    actors: "James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter",
    plot: "A wheelchair-bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
  },
  {
    id: 20,
    title: "12 Angry Men",
    year: "1957",
    runtime: "96",
    genres: ["Crime", "Drama"],
    director: "Sidney Lumet",
    actors: "Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall",
    plot: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SX300.jpg",
  },
  {
    id: 21,
    title: "Reservoir Dogs",
    year: "1992",
    runtime: "99",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Quentin Tarantino",
    actors: "Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn",
    plot: "After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjE5ZDJiZTQtOGE2YS00ZTc5LTk0OGUtOTg2NjdjZmVlYzE2XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg",
  },
  {
    id: 22,
    title: "Shogun",
    year: "1980",
    runtime: "60",
    genres: ["Adventure", "Drama"],
    director: "N/A",
    actors: "Richard Chamberlain, Toshirô Mifune, Yôko Shimada, Furankî Sakai",
    plot: "A English navigator becomes both a player and pawn in the complex political games in feudal Japan.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY1ODI4NzYxMl5BMl5BanBnXkFtZTcwNDA4MzUxMQ@@._V1_SX300.jpg",
  },
  {
    id: 23,
    title: "The Hobbit: An Unexpected Journey",
    year: "2012",
    runtime: "169",
    genres: ["Adventure", "Fantasy"],
    director: "Peter Jackson",
    actors: "Ian McKellen, Martin Freeman, Richard Armitage, Ken Stott",
    plot: "A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_SX300.jpg",
  },
  {
    id: 24,
    title: "The Great Beauty",
    year: "2013",
    runtime: "141",
    genres: ["Drama"],
    director: "Paolo Sorrentino",
    actors: "Toni Servillo, Carlo Verdone, Sabrina Ferilli, Carlo Buccirosso",
    plot: "Jep Gambardella has seduced his way through the lavish nightlife of Rome for decades, but after his 65th birthday and a shock from the past, Jep looks past the nightclubs and parties to find a timeless landscape of absurd, exquisite beauty.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ0ODg1OTQ2Nl5BMl5BanBnXkFtZTgwNTc2MDY1MDE@._V1_SX300.jpg",
  },

  {
    id: 25,
    title: "Mary and Max",
    year: "2009",
    runtime: "92",
    genres: ["Animation", "Comedy", "Drama"],
    director: "Adam Elliot",
    actors: "Toni Collette, Philip Seymour Hoffman, Barry Humphries, Eric Bana",
    plot: "A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year old, severely obese man living in New York.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1NDIyNTA1Nl5BMl5BanBnXkFtZTcwMjc2Njk3OA@@._V1_SX300.jpg",
  },
  {
    id: 26,
    title: "Flight",
    year: "2012",
    runtime: "138",
    genres: ["Drama", "Thriller"],
    director: "Robert Zemeckis",
    actors:
      "Nadine Velazquez, Denzel Washington, Carter Cabassa, Adam C. Edwards",
    plot: "An airline pilot saves almost all his passengers on his malfunctioning airliner which eventually crashed, but an investigation into the accident reveals something troubling.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxMjI1OTMxNl5BMl5BanBnXkFtZTcwNjc3NTY1OA@@._V1_SX300.jpg",
  },
  {
    id: 27,
    title: "One Flew Over the Cuckoo's Nest",
    year: "1975",
    runtime: "133",
    genres: ["Drama"],
    director: "Milos Forman",
    actors: "Michael Berryman, Peter Brocco, Dean R. Brooks, Alonzo Brown",
    plot: "A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BYmJkODkwOTItZThjZC00MTE0LWIxNzQtYTM3MmQwMGI1OWFiXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
  },
  {
    id: 28,
    title: "Requiem for a Dream",
    year: "2000",
    runtime: "102",
    genres: ["Drama"],
    director: "Darren Aronofsky",
    actors: "Ellen Burstyn, Jared Leto, Jennifer Connelly, Marlon Wayans",
    plot: "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzODMzODYwOF5BMl5BanBnXkFtZTcwODM2NjA2NQ@@._V1_SX300.jpg",
  },
  {
    id: 29,
    title: "The Truman Show",
    year: "1998",
    runtime: "103",
    genres: ["Comedy", "Drama", "Sci-Fi"],
    director: "Peter Weir",
    actors: "Jim Carrey, Laura Linney, Noah Emmerich, Natascha McElhone",
    plot: "An insurance salesman/adjuster discovers his entire life is actually a television show.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
  },
  {
    id: 30,
    title: "The Artist",
    year: "2011",
    runtime: "100",
    genres: ["Comedy", "Drama", "Romance"],
    director: "Michel Hazanavicius",
    actors: "Jean Dujardin, Bérénice Bejo, John Goodman, James Cromwell",
    plot: "A silent movie star meets a young dancer, but the arrival of talking pictures sends their careers in opposite directions.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzk0NzQxMTM0OV5BMl5BanBnXkFtZTcwMzU4MDYyNQ@@._V1_SX300.jpg",
  },

  {
    id: 31,
    title: "The Hobbit: The Desolation of Smaug",
    year: "2013",
    runtime: "161",
    genres: ["Adventure", "Fantasy"],
    director: "Peter Jackson",
    actors: "Ian McKellen, Martin Freeman, Richard Armitage, Ken Stott",
    plot: "The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug. Bilbo Baggins is in possession of a mysterious and magical ring.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_SX300.jpg",
  },
  {
    id: 32,
    title: "Vicky Cristina Barcelona",
    year: "2008",
    runtime: "96",
    genres: ["Drama", "Romance"],
    director: "Woody Allen",
    actors:
      "Rebecca Hall, Scarlett Johansson, Christopher Evan Welch, Chris Messina",
    plot: "Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2NDQ4MTg2MV5BMl5BanBnXkFtZTcwNDUzNjU3MQ@@._V1_SX300.jpg",
  },

  {
    id: 33,
    title: "Lost in Translation",
    year: "2003",
    runtime: "101",
    genres: ["Drama"],
    director: "Sofia Coppola",
    actors:
      "Scarlett Johansson, Bill Murray, Akiko Takeshita, Kazuyoshi Minamimagoe",
    plot: "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI2NDI5ODk4N15BMl5BanBnXkFtZTYwMTI3NTE3._V1_SX300.jpg",
  },
  {
    id: 34,
    title: "Match Point",
    year: "2005",
    runtime: "119",
    genres: ["Drama", "Romance", "Thriller"],
    director: "Woody Allen",
    actors:
      "Jonathan Rhys Meyers, Alexander Armstrong, Paul Kaye, Matthew Goode",
    plot: "At a turning point in his life, a former tennis pro falls for an actress who happens to be dating his friend and soon-to-be brother-in-law.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzNzY4MzE5NF5BMl5BanBnXkFtZTcwMzQ1MDMzMQ@@._V1_SX300.jpg",
  },

  {
    id: 35,
    title: "Madagascar: Escape 2 Africa",
    year: "2008",
    runtime: "89",
    genres: ["Animation", "Action", "Adventure"],
    director: "Eric Darnell, Tom McGrath",
    actors: "Ben Stiller, Chris Rock, David Schwimmer, Jada Pinkett Smith",
    plot: "The animals try to fly back to New York City, but crash-land on an African wildlife refuge, where Alex is reunited with his parents.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjExMDA4NDcwMl5BMl5BanBnXkFtZTcwODAxNTQ3MQ@@._V1_SX300.jpg",
  },
  {
    id: 36,
    title: "Despicable Me 2",
    year: "2013",
    runtime: "98",
    genres: ["Animation", "Adventure", "Comedy"],
    director: "Pierre Coffin, Chris Renaud",
    actors: "Steve Carell, Kristen Wiig, Benjamin Bratt, Miranda Cosgrove",
    plot: "When Gru, the world's most super-bad turned super-dad has been recruited by a team of officials to stop lethal muscle and a host of Gru's own, He has to fight back with new gadgetry, cars, and more minion madness.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjExNjAyNTcyMF5BMl5BanBnXkFtZTgwODQzMjQ3MDE@._V1_SX300.jpg",
  },
  {
    id: 37,
    title: "City of God",
    year: "2002",
    runtime: "130",
    genres: ["Crime", "Drama"],
    director: "Fernando Meirelles, Kátia Lund",
    actors:
      "Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva",
    plot: "Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX300.jpg",
  },
  {
    id: 38,
    title: "Madagascar",
    year: "2005",
    runtime: "86",
    genres: ["Animation", "Adventure", "Comedy"],
    director: "Eric Darnell, Tom McGrath",
    actors: "Ben Stiller, Chris Rock, David Schwimmer, Jada Pinkett Smith",
    plot: "Spoiled by their upbringing with no idea what wild life is really like, four animals from New York Central Zoo escape, unwittingly assisted by four absconding penguins, and find themselves in Madagascar, among a bunch of merry lemurs",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4NDUwMzQxMF5BMl5BanBnXkFtZTcwMDgwNjgyMQ@@._V1_SX300.jpg",
  },
  {
    id: 39,
    title: "Madagascar 3: Europe's Most Wanted",
    year: "2012",
    runtime: "93",
    genres: ["Animation", "Adventure", "Comedy"],
    director: "Eric Darnell, Tom McGrath, Conrad Vernon",
    actors: "Ben Stiller, Chris Rock, David Schwimmer, Jada Pinkett Smith",
    plot: "Alex, Marty, Gloria and Melman are still fighting to get home to their beloved Big Apple. Their journey takes them through Europe where they find the perfect cover: a traveling circus, which they reinvent - Madagascar style.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2MTIzNzk2MF5BMl5BanBnXkFtZTcwMDcwMzQxNw@@._V1_SX300.jpg",
  },
  {
    id: 40,
    title: "God Bless America",
    year: "2011",
    runtime: "105",
    genres: ["Comedy", "Crime"],
    director: "Bobcat Goldthwait",
    actors:
      "Joel Murray, Tara Lynne Barr, Melinda Page Hamilton, Mackenzie Brooke Smith",
    plot: "On a mission to rid society of its most repellent citizens, terminally ill Frank makes an unlikely accomplice in 16-year-old Roxy.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwMTc1MzA4NF5BMl5BanBnXkFtZTcwNzQwMTgzNw@@._V1_SX300.jpg",
  },
  {
    id: 41,
    title: "The Social Network",
    year: "2010",
    runtime: "120",
    genres: ["Biography", "Drama"],
    director: "David Fincher",
    actors: "Jesse Eisenberg, Rooney Mara, Bryan Barter, Dustin Fitzsimons",
    plot: "Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the co-founder who was later squeezed out of the business.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2ODk0NDAwMF5BMl5BanBnXkFtZTcwNTM1MDc2Mw@@._V1_SX300.jpg",
  },

  {
    id: 42,
    title: "American Gangster",
    year: "2007",
    runtime: "157",
    genres: ["Biography", "Crime", "Drama"],
    director: "Ridley Scott",
    actors: "Denzel Washington, Russell Crowe, Chiwetel Ejiofor, Josh Brolin",
    plot: "In 1970s America, a detective works to bring down the drug empire of Frank Lucas, a heroin kingpin from Manhattan, who is smuggling the drug into the country from the Far East.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkyNzY5MDA5MV5BMl5BanBnXkFtZTcwMjg4MzI3MQ@@._V1_SX300.jpg",
  },
  {
    id: 43,
    title: "Catch Me If You Can",
    year: "2002",
    runtime: "141",
    genres: ["Biography", "Crime", "Drama"],
    director: "Steven Spielberg",
    actors: "Leonardo DiCaprio, Tom Hanks, Christopher Walken, Martin Sheen",
    plot: "The true story of Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars' worth of checks as a Pan Am pilot, doctor, and legal prosecutor.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg",
  },
  {
    id: 44,
    title: "American History X",
    year: "1998",
    runtime: "119",
    genres: ["Crime", "Drama"],
    director: "Tony Kaye",
    actors: "Edward Norton, Edward Furlong, Beverly D'Angelo, Jennifer Lien",
    plot: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0MTM4MTQtNzY5MC00NzY3LWI1ZTgtYzcxMjkyMzU4MDZiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
  },

  {
    id: 45,
    title: "Pirates of the Caribbean: At World's End",
    year: "2007",
    runtime: "169",
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Gore Verbinski",
    actors: "Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley",
    plot: "Captain Barbossa, Will Turner and Elizabeth Swann must sail off the edge of the map, navigate treachery and betrayal, find Jack Sparrow, and make their final alliances for one last decisive battle.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIyNjkxNzEyMl5BMl5BanBnXkFtZTYwMjc3MDE3._V1_SX300.jpg",
  },
  {
    id: 46,
    title: "Crash",
    year: "2004",
    runtime: "112",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Paul Haggis",
    actors: "Karina Arroyave, Dato Bakhtadze, Sandra Bullock, Don Cheadle",
    plot: "Los Angeles citizens with vastly separate lives collide in interweaving stories of race, loss and redemption.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BOTk1OTA1MjIyNV5BMl5BanBnXkFtZTcwODQxMTkyMQ@@._V1_SX300.jpg",
  },
  {
    id: 47,
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    year: "2003",
    runtime: "143",
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Gore Verbinski",
    actors: "Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley",
    plot: "Blacksmith Will Turner teams up with eccentric pirate \"Captain\" Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAyNDM4MTc2N15BMl5BanBnXkFtZTYwNDk0Mjc3._V1_SX300.jpg",
  },

  {
    id: 48,
    title: "Oldboy",
    year: "2003",
    runtime: "120",
    genres: ["Drama", "Mystery", "Thriller"],
    director: "Chan-wook Park",
    actors: "Min-sik Choi, Ji-tae Yu, Hye-jeong Kang, Dae-han Ji",
    plot: "After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_SX300.jpg",
  },
  {
    id: 49,
    title: "Chocolat",
    year: "2000",
    runtime: "121",
    genres: ["Drama", "Romance"],
    director: "Lasse Hallström",
    actors:
      "Alfred Molina, Carrie-Anne Moss, Aurelien Parent Koenig, Antonio Gil",
    plot: "A woman and her daughter open a chocolate shop in a small French village that shakes up the rigid morality of the community.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4MDI3NTQwMV5BMl5BanBnXkFtZTcwNjIzNDcyMQ@@._V1_SX300.jpg",
  },
  {
    id: 50,
    title: "Casino Royale",
    year: "2006",
    runtime: "144",
    genres: ["Action", "Adventure", "Thriller"],
    director: "Martin Campbell",
    actors: "Daniel Craig, Eva Green, Mads Mikkelsen, Judi Dench",
    plot: "Armed with a licence to kill, Secret Agent James Bond sets out on his first mission as 007 and must defeat a weapons dealer in a high stakes game of poker at Casino Royale, but things are not what they seem.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM5MjI4NDExNF5BMl5BanBnXkFtZTcwMDM1MjMzMQ@@._V1_SX300.jpg",
  },
  {
    id: 51,
    title: "WALL·E",
    year: "2008",
    runtime: "98",
    genres: ["Animation", "Adventure", "Family"],
    director: "Andrew Stanton",
    actors: "Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard",
    plot: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczOTA3MzY2N15BMl5BanBnXkFtZTcwOTYwNjE2MQ@@._V1_SX300.jpg",
  },
  {
    id: 52,
    title: "The Wolf of Wall Street",
    year: "2013",
    runtime: "180",
    genres: ["Biography", "Comedy", "Crime"],
    director: "Martin Scorsese",
    actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
    plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
  },
  {
    id: 53,
    title: "Hellboy II: The Golden Army",
    year: "2008",
    runtime: "120",
    genres: ["Action", "Adventure", "Fantasy"],
    director: "Guillermo del Toro",
    actors: "Ron Perlman, Selma Blair, Doug Jones, John Alexander",
    plot: "The mythical world starts a rebellion against humanity in order to rule the Earth, so Hellboy and his team must save the world from the rebellious creatures.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5NzgyMjc2Nl5BMl5BanBnXkFtZTcwOTU3MDI3MQ@@._V1_SX300.jpg",
  },
  {
    id: 54,
    title: "I-See-You.Com",
    year: "2006",
    runtime: "92",
    genres: ["Comedy"],
    director: "Eric Steven Stahl",
    actors: "Beau Bridges, Rosanna Arquette, Mathew Botuchis, Shiri Appleby",
    plot: "A 17-year-old boy buys mini-cameras and displays the footage online at I-see-you.com. The cash rolls in as the site becomes a major hit. Everyone seems to have fun until it all comes crashing down....",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwMDUzNzA5Nl5BMl5BanBnXkFtZTcwMjQ2Njk3MQ@@._V1_SX300.jpg",
  },
  {
    id: 55,
    title: "The Grand Budapest Hotel",
    year: "2014",
    runtime: "99",
    genres: ["Adventure", "Comedy", "Crime"],
    director: "Wes Anderson",
    actors: "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody",
    plot: "The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
  },
  {
    id: 56,
    title: "Once Upon a Time in America",
    year: "1984",
    runtime: "229",
    genres: ["Crime", "Drama"],
    director: "Sergio Leone",
    actors: "Robert De Niro, James Woods, Elizabeth McGovern, Joe Pesci",
    plot: "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
  },
  {
    id: 57,
    title: "Oblivion",
    year: "2013",
    runtime: "124",
    genres: ["Action", "Adventure", "Mystery"],
    director: "Joseph Kosinski",
    actors: "Tom Cruise, Morgan Freeman, Olga Kurylenko, Andrea Riseborough",
    plot: "A veteran assigned to extract Earth's remaining resources begins to question what he knows about his mission and himself.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwMDY0MTA4MF5BMl5BanBnXkFtZTcwNzI3MDgxOQ@@._V1_SX300.jpg",
  },
  {
    id: 58,
    title: "V for Vendetta",
    year: "2005",
    runtime: "132",
    genres: ["Action", "Drama", "Thriller"],
    director: "James McTeigue",
    actors: "Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry",
    plot: 'In a future British tyranny, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow it with the help of a young woman.',
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SX300.jpg",
  },
  {
    id: 59,
    title: "Gattaca",
    year: "1997",
    runtime: "106",
    genres: ["Drama", "Sci-Fi", "Thriller"],
    director: "Andrew Niccol",
    actors: "Ethan Hawke, Uma Thurman, Gore Vidal, Xander Berkeley",
    plot: "A genetically inferior man assumes the identity of a superior one in order to pursue his lifelong dream of space travel.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDQxOTc0MzMtZmRlOS00OWQ5LWI2ZDctOTAwNmMwOTYxYzlhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
  },
  {
    id: 60,
    title: "Silver Linings Playbook",
    year: "2012",
    runtime: "122",
    genres: ["Comedy", "Drama", "Romance"],
    director: "David O. Russell",
    actors: "Bradley Cooper, Jennifer Lawrence, Robert De Niro, Jacki Weaver",
    plot: "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_SX300.jpg",
  },
  {
    id: 61,
    title: "Alice in Wonderland",
    year: "2010",
    runtime: "108",
    genres: ["Adventure", "Family", "Fantasy"],
    director: "Tim Burton",
    actors: "Johnny Depp, Mia Wasikowska, Helena Bonham Carter, Anne Hathaway",
    plot: "Nineteen-year-old Alice returns to the magical world from her childhood adventure, where she reunites with her old friends and learns of her true destiny: to end the Red Queen's reign of terror.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMwNjAxMTc0Nl5BMl5BanBnXkFtZTcwODc3ODk5Mg@@._V1_SX300.jpg",
  },
  {
    id: 62,
    title: "Pacific Rim",
    year: "2013",
    runtime: "131",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Guillermo del Toro",
    actors: "Charlie Hunnam, Diego Klattenhoff, Idris Elba, Rinko Kikuchi",
    plot: "As a war between humankind and monstrous sea creatures wages on, a former pilot and a trainee are paired up to drive a seemingly obsolete special weapon in a desperate effort to save the world from the apocalypse.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY3MTI5NjQ4Nl5BMl5BanBnXkFtZTcwOTU1OTU0OQ@@._V1_SX300.jpg",
  },
  {
    id: 63,
    title: "Cloud Atlas",
    year: "2012",
    runtime: "172",
    genres: ["Drama", "Sci-Fi"],
    director: "Tom Tykwer, Lana Wachowski, Lilly Wachowski",
    actors: "Tom Hanks, Halle Berry, Jim Broadbent, Hugo Weaving",
    plot: "An exploration of how the actions of individual lives impact one another in the past, present and future, as one soul is shaped from a killer into a hero, and an act of kindness ripples across centuries to inspire a revolution.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_SX300.jpg",
  },
  {
    id: 64,
    title: "The Impossible",
    year: "2012",
    runtime: "114",
    genres: ["Drama", "Thriller"],
    director: "J.A. Bayona",
    actors: "Naomi Watts, Ewan McGregor, Tom Holland, Samuel Joslin",
    plot: "The story of a tourist family in Thailand caught in the destruction and chaotic aftermath of the 2004 Indian Ocean tsunami.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5NTA3NzQ5Nl5BMl5BanBnXkFtZTcwOTYxNjY0OA@@._V1_SX300.jpg",
  },
  {
    id: 65,
    title: "All Quiet on the Western Front",
    year: "1930",
    runtime: "136",
    genres: ["Drama", "War"],
    director: "Lewis Milestone",
    actors: "Louis Wolheim, Lew Ayres, John Wray, Arnold Lucy",
    plot: "A young soldier faces profound disillusionment in the soul-destroying horror of World War I.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNTM5OTg2NDY1NF5BMl5BanBnXkFtZTcwNTQ4MTMwNw@@._V1_SX300.jpg",
  },
  {
    id: 66,
    title: "Dallas Buyers Club",
    year: "2013",
    runtime: "117",
    genres: ["Biography", "Drama"],
    director: "Jean-Marc Vallée",
    actors: "Matthew McConaughey, Jennifer Garner, Jared Leto, Denis O'Hare",
    plot: "In 1985 Dallas, electrician and hustler Ron Woodroof works around the system to help AIDS patients get the medication they need after he is diagnosed with the disease.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwMTA4MzgyNF5BMl5BanBnXkFtZTgwMjEyMjE0MDE@._V1_SX300.jpg",
  },
  {
    id: 67,
    title: "Before Sunrise",
    year: "1995",
    runtime: "105",
    genres: ["Drama", "Romance"],
    director: "Richard Linklater",
    actors: "Ethan Hawke, Julie Delpy, Andrea Eckert, Hanno Pöschl",
    plot: "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyMTM3MTQxMl5BMl5BanBnXkFtZTcwMDAzNjQ4Mg@@._V1_SX300.jpg",
  },
  {
    id: 68,
    title: "Boyhood",
    year: "2014",
    runtime: "165",
    genres: ["Drama"],
    director: "Richard Linklater",
    actors:
      "Ellar Coltrane, Patricia Arquette, Elijah Smith, Lorelei Linklater",
    plot: "The life of Mason, from early childhood to his arrival at college.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYzNDc2MDc0N15BMl5BanBnXkFtZTgwOTcwMDQ5MTE@._V1_SX300.jpg",
  },
  {
    id: 69,
    title: "Chinatown",
    year: "1974",
    runtime: "130",
    genres: ["Drama", "Mystery", "Thriller"],
    director: "Roman Polanski",
    actors: "Jack Nicholson, Faye Dunaway, John Huston, Perry Lopez",
    plot: "A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption and murder.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BN2YyNDE5NzItMjAwNC00MGQxLTllNjktZGIzMWFkZjA3OWQ0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
  },
  {
    id: 70,
    title: "Calvary",
    year: "2014",
    runtime: "102",
    genres: ["Comedy", "Drama"],
    director: "John Michael McDonagh",
    actors: "Brendan Gleeson, Chris O'Dowd, Kelly Reilly, Aidan Gillen",
    plot: "After he is threatened during a confession, a good-natured priest must battle the dark forces closing in around him.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3MjQ1MjE2M15BMl5BanBnXkFtZTgwNTMzNjE4MTE@._V1_SX300.jpg",
  },
  {
    id: 71,
    title: "Spirited Away",
    year: "2001",
    runtime: "125",
    genres: ["Animation", "Adventure", "Family"],
    director: "Hayao Miyazaki",
    actors: "Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naitô",
    plot: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjYxMDcyMzIzNl5BMl5BanBnXkFtZTYwNDg2MDU3._V1_SX300.jpg",
  },
  {
    id: 72,
    title: "Indochine",
    year: "1992",
    runtime: "159",
    genres: ["Drama", "Romance"],
    director: "Régis Wargnier",
    actors: "Catherine Deneuve, Vincent Perez, Linh Dan Pham, Jean Yanne",
    plot: "This story is set in 1930, at the time when French colonial rule in Indochina is ending. A widowed French woman who works in the rubber fields, raises a Vietnamese princess as if she was ...",
    posterUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1MTkzNzA3NF5BMl5BanBnXkFtZTYwNTI2MzU5._V1_SX300.jpg",
  },
];
